apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: tutum/dnsutils
    command:
    - /bin/bash
    - -c
    - --
    args:
    - while true; do sleep 30; done;
